### ISSUE TITLE
Open something detached

### ISSUE THREAD

**Issue by RedstoneMedia** [Byron/open-rs#44]
It would be nice, if it was possible to open something, but not have the program be a child of the process.

**Comment by Byron** [comment]
Thanks for the suggestion!

Do you mind sharing an actual usecase for daemonizing something? To me it sounds like a workaround for something else.

**Comment by RedstoneMedia** [comment]
In my case, I'm trying to open a steam game link (steam://rungameid/<someid>). But some programs don't expect to be a child of some random process and start to show unexpected behavior. It's not a very common problem, so it would be understandable, if you didn't want to implement it, but I still wanted to try making a feature request.

**Comment by Byron** [comment]
Indeed I would refrain from putting in support for daemonization into `open`, but since I am lacking a lot of knowledge in that realm I hoped there might be some middle ground just for these kind of programs.

Maybe you could try [`daemonize`](https://crates.io/crates/daemonize) for your use-case by manually daemonizing the program while providing it the URL as argument. If this works, I can imagine adding an API behind the `daemon` (or similar) feature toggle to add this functionality to `open`.

**Comment by shirshak55** [comment]
In Linux, it shouldn't be a problem because init is always parent of some process?

**Comment by Byron** [comment]
I believe this is fixed with the latest major release, see [this comment](https://github.com/Byron/open-rs/issues/46#issuecomment-1153041087) for more information.

If not, please do let me know.
